#
# This file contains configuration flags for the site
#

# Name of your site (displayed in the header)
title: Useless Programming

# Site Tagline (displayed in the header)
tagline: Code. Connect. Contribute.

# Site Description 
description: Learn strange programming languages

# Your website URL 
url: http://rmittpc.club/useless-programming

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/useless-programming"

# !! You don't need to change any of the configuration flags below !!
permalink: /:title/

# This will require each of these plugins automatically.
plugins: []

# Build settings
markdown: kramdown

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
